# Generated by Django 3.2.6 on 2023-07-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
